### ISSUE TITLE
Document Generation

### ISSUE THREAD

**Issue by truongdavid98** [opencaesar/firesat-example#6]
## User Story
As a developer I would like to use the DocBook Document generator so that there will be an example document of Firesat that is continually updated with Firesat

## Detailed Description
Use the DocBook document generator to create a document on firesat's design. Publish the html to github pages and the pdf to bintray. 

## Acceptance Criteria
- [x] Given the docbook document with tags, then output a docbook with its tags replaced with proper data from sparql queries
- [ ] Given a docbook, then publish an HTML render of it to GitHub pages
- [ ] Given a docbook, then publish a PDF render of it to bintray

## Sub-task List
- [x] Create a gradle task to download the necessary XSLs for the DocBook generator
- [ ] Create a fuseki server 
- [x] Upload the necessary OML->OWL files to the server 
- [x] Create an example document
- [x] Execute queries on this server 
- [x] Execute tag replacement using the frames from the query via Gradle Task
- [x] Execute HTML rendering and publish to GitHub Pages via Gradle Task
- [x] Execute PDF rendering and publish to Bintray via Gradle Task
